In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics import roc_auc_score
df = pd.read_csv(r"C:\Users\adith\Downloads\finalprojdataset.zip")
X = df.drop(columns=['label', 'title', 'author', 'text', 'date_published', 'source'])
y = df['label']
categorical_cols = ['state', 'category', 'political_bias', 'fact_check_rating']

le = LabelEncoder()
for col in categorical_cols:
    X[col] = le.fit_transform(X[col])
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=47)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
y_proba = model.predict_proba(X_test)[:, 1]

roc_score = roc_auc_score(y_test, y_proba)
print("ROC", roc_score)

Accuracy: 0.52625
Confusion Matrix:
 [[219 207]
 [172 202]]
Classification Report:
               precision    recall  f1-score   support

        Fake       0.56      0.51      0.54       426
        Real       0.49      0.54      0.52       374

    accuracy                           0.53       800
   macro avg       0.53      0.53      0.53       800
weighted avg       0.53      0.53      0.53       800

ROC 0.508178303331576


In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score

df = pd.read_csv(r"C:\Users\adith\Downloads\finalprojdataset.zip")
selected_features = ['sentiment_score', 'clickbait_score', 'plagiarism_score']
X = df[selected_features]
y = df['label']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=47)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

y_proba = model.predict_proba(X_test)[:, 1]
roc_score = roc_auc_score(y_test, y_proba)
print("ROC:", roc_score)


Accuracy: 0.52
Confusion Matrix:
 [[233 193]
 [191 183]]
Classification Report:
               precision    recall  f1-score   support

        Fake       0.55      0.55      0.55       426
        Real       0.49      0.49      0.49       374

    accuracy                           0.52       800
   macro avg       0.52      0.52      0.52       800
weighted avg       0.52      0.52      0.52       800

ROC: 0.510538274208531


In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score


df = pd.read_csv(r"C:\Users\adith\Downloads\finalprojdataset.zip")


X = df.drop(columns=['label', 'title', 'author', 'text', 'date_published', 'source'])
y = df['label']

categorical_cols = ['state', 'category', 'political_bias', 'fact_check_rating']
le = LabelEncoder()
for col in categorical_cols:
    X[col] = le.fit_transform(X[col])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=47)


model = RandomForestClassifier(random_state=47)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
y_proba = model.predict_proba(X_test)[:, 1]
roc_score = roc_auc_score(y_test, y_proba)
print("ROC:", roc_score)


Accuracy: 0.50625
Confusion Matrix:
 [[213 213]
 [182 192]]
Classification Report:
               precision    recall  f1-score   support

        Fake       0.54      0.50      0.52       426
        Real       0.47      0.51      0.49       374

    accuracy                           0.51       800
   macro avg       0.51      0.51      0.51       800
weighted avg       0.51      0.51      0.51       800

ROC: 0.5054919535035525
